### ISSUE TITLE
Second vote with a different wallet fails

### ISSUE THREAD

**Issue by Faustino-CIMA** [input-output-hk/jorvot#11]
Hi, 

I used the windows v1.0.1 default version to vote. After voting, I checked the transaction in the cardano explorer and it went through without a problem. After I wanted to vote from the same computer with a diffrent wallet and it didn't work anymore. From jorvot perspective everything worked fine, but when I checked the transaction, it throwed an invalid search at me.

best regards, 

Faustino

**Comment by mark-stopka** [comment]
Can you please post the fragment (transaction) ID of the second vote you tried to cast?

**Comment by Faustino-CIMA** [comment]
Here it is mark:

a3ed921038280d0f74bdf849fd5f2e9be0a0585fe6f97eadf9820b3c3d460180

I tried again with a fresh signed copy of jorvot v1.0.1 with the same result, it's strange, it generated the same fragment.

**Comment by Faustino-CIMA** [comment]
It's not an issue Mark, sorry for the false alarm. The transaction just took a lot longer as I thought, it actually went through after midnight, so everything works fine.

Thank you for your great work and support, 

best resgards,

Faustino
